name: CI

on: [push]

env:
  LLVM_VERSION: 19.1.5

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
        arch:
          - win64
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: seanmiddleditch/gha-setup-ninja@96bed6edff20d1dd61ecff9b75cc519d516e6401
      - shell: pwsh
        run: .\build-llvm.ps1
      - shell: pwsh
        run: Compress-Archive -Path llvm -DestinationPath llvm-${{ env.LLVM_VERSION }}-${{ matrix.arch }}-msvc${{ env.VisualStudioVersion }}.zip
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-msvc${{ env.VisualStudioVersion }}
          path: llvm*msvc${{ env.VisualStudioVersion }}.zip

  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
    steps:
      - uses: actions/checkout@v4
      - run: brew install ninja
      - run: ./build-llvm.sh build llvm
      - run: zip -r llvm-${{ env.LLVM_VERSION }}-${{ matrix.os }}.zip llvm
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: llvm*${{ matrix.os }}.zip

  release:
    name: Build release
    runs-on: ubuntu-latest
    needs:
      - windows
      - macos
    steps:
      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          export GITHUB_TAG=$(echo ${GITHUB_TAG#refs/heads/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: macos-14

      - uses: actions/download-artifact@v4
        with:
          name: macos-15

      - uses: actions/download-artifact@v4
        with:
          name: win64-msvc16.0

      - uses: actions/download-artifact@v4
        with:
          name: win64-msvc17.0

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, 'beta') }}
          generate_release_notes: false
          files: |
            *.zip
